nelmio_cors:
    defaults:
        origin_regex: false
        allow_credentials: false
        allow_origin: []
        allow_methods: []
        allow_headers: []
        expose_headers: []
        max_age: 0
        skip_same_as_origin: true
    paths:
        '^/':
            max_age: 3600
            allow_credentials: true
            origin_regex: true
            allow_origin:
                - '^http://localhost:[0-9]+'
            allow_headers:
                - '*'
            allow_methods:
                - POST
                - PUT
                - GET
                - PATCH
                - DELETE